/**
 * @file
 * @author chris
 * @brief RAII, move-only 2D GPU image backed by VMA, bundled with a default image view.
 *
 * L1 resource that owns a `VkImage`, a `VmaAllocation`, and a `VkImageView`, and frees all
 * three on destruction. Allocation is done through @ref veng::Image::create; the resulting object
 * is non-copyable and must be moved or held inside a @ref veng::ResourcePool copy slot.
 *
 * @ingroup resources
 */

#ifndef VENG_IMAGE_HPP
#define VENG_IMAGE_HPP

#include <cstdint>
#include <expected>
#include <veng/rhi/Device.hpp>
#include <vulkan-memory-allocator-hpp/vk_mem_alloc.hpp>
#include <vulkan/vulkan.hpp>

namespace veng
{
/**
 * @brief RAII, move-only 2D GPU image with a matching default image view.
 * @ingroup resources
 * @see ResourcePool
 */
class Image
{
	 public:
	/**
	 * @brief Allocate a device-local 2D image and a matching view spanning all mip levels.
	 *
	 * Creates a 2D image with `mip_levels` mips, 1 array layer, `samples` samples, optimal
	 * tiling, and a view over the full mip range with the given `aspect`. When `mip_levels` > 1
	 * the usage must include `eTransferSrc | eTransferDst` so the mip chain can be
	 * generated by blitting between levels after upload. The default value of 1 preserves
	 * the single-level render-target behaviour. A multisampled image (`samples` > `e1`) must
	 * have a single mip level — the MSAA color/depth attachment of a render pass.
	 *
	 * A view is created only when `usage` contains at least one view-capable flag
	 * (sampled, storage, colour/depth attachment, input attachment, or transient
	 * attachment); a transfer-only image gets a null view handle.
	 *
	 * @param allocator  The VMA allocator to allocate device memory from.
	 * @param device     The Vulkan logical device used to create the image view.
	 * @param rhi        The RHI registry the image registers its handle with (released on destroy).
	 * @param extent     Width and height of the image in texels.
	 * @param format     Pixel format.
	 * @param usage      Vulkan image-usage flags.
	 * @param aspect     View aspect mask (colour or depth).
	 * @param mip_levels Number of mip levels; 0 is treated as 1.
	 * @param samples    Sample count; `e1` for a normal image, higher for an MSAA attachment.
	 * @return The constructed @ref veng::Image on success, or the `vk::Result` error code on failure.
	 */
	[[nodiscard]] static std::expected<Image, vk::Result> create(
		vma::Allocator allocator, vk::Device device, rhi::Device& rhi, vk::Extent2D extent, vk::Format format,
		vk::ImageUsageFlags usage, vk::ImageAspectFlags aspect = vk::ImageAspectFlagBits::eColor,
		std::uint32_t mip_levels = 1, vk::SampleCountFlagBits samples = vk::SampleCountFlagBits::e1);

	/**
	 * @brief Allocate an image in RHI vocabulary — a caller names only `rhi::` types (no `vk::`/`vma::`).
	 *
	 * The higher-level overload for L4/L5 callers (asset loaders, post-process passes): it derives the
	 * device and allocator from @p rhi and infers the view aspect from @p usage (depth when the usage
	 * includes `DEPTH_ATTACHMENT`, colour otherwise). Same multi-mip / view-creation rules as the
	 * low-level overload above.
	 *
	 * @param rhi        The RHI device the image registers its handle with (and whose device/allocator back it).
	 * @param extent     Width and height of the image in texels.
	 * @param format     Pixel format.
	 * @param usage      RHI texture-usage capability flags (sampled, attachment, transfer).
	 * @param mip_levels Number of mip levels; 0 is treated as 1.
	 * @param samples    Sample count; `X1` for a normal image, higher for an MSAA attachment.
	 * @return The constructed @ref veng::Image on success, or the `vk::Result` error code on failure.
	 */
	[[nodiscard]] static std::expected<Image, vk::Result> create(rhi::Device& rhi, rhi::Extent2D extent,
																 rhi::Format format, rhi::TextureUsageFlags usage,
																 std::uint32_t	   mip_levels = 1,
																 rhi::SampleCount samples = rhi::SampleCount::X1);

	Image(const Image&)			   = delete;
	Image& operator=(const Image&) = delete;
	Image(Image&& other) noexcept;
	Image& operator=(Image&& other) noexcept;
	~Image();

	/// @brief The underlying Vulkan image handle.
	[[nodiscard]] vk::Image image() const noexcept { return m_image; }
	/// @brief The default image view spanning all mip levels, or a null handle for transfer-only images.
	[[nodiscard]] vk::ImageView view() const noexcept { return m_view; }
	/// @brief The pixel format of the image.
	[[nodiscard]] vk::Format format() const noexcept { return m_format; }
	/// @brief The width and height of the image in texels.
	[[nodiscard]] vk::Extent2D extent() const noexcept { return m_extent; }
	/// @brief The number of mip levels in the image.
	[[nodiscard]] std::uint32_t mip_levels() const noexcept { return m_mip_levels; }
	/// @brief The sample count of the image (`e1` unless this is an MSAA attachment).
	[[nodiscard]] vk::SampleCountFlagBits sample_count() const noexcept { return m_sample_count; }
	/// @brief The RHI handle this image is registered under (flows on `ImageRef`).
	[[nodiscard]] rhi::TextureHandle handle() const noexcept { return m_handle; }

	 private:
	Image(vma::Allocator allocator, vk::Device device, rhi::Device& rhi, rhi::TextureHandle handle, vk::Image image,
		  vma::Allocation allocation, vk::ImageView view, vk::Format format, vk::Extent2D extent,
		  std::uint32_t mip_levels, vk::SampleCountFlagBits samples) noexcept;
	void destroy() noexcept;

	vma::Allocator			m_allocator;
	vk::Device				m_device;
	rhi::Device*			m_rhi;	  ///< Registry to release @ref m_handle into on destroy.
	rhi::TextureHandle		m_handle; ///< This image's registered handle.
	vk::Image				m_image;
	vma::Allocation			m_allocation;
	vk::ImageView			m_view;
	vk::Format				m_format;
	vk::Extent2D			m_extent;
	std::uint32_t			m_mip_levels;
	vk::SampleCountFlagBits m_sample_count;
};
} // namespace veng

#endif // VENG_IMAGE_HPP
