/**
 * @file
 * @author chris
 * @brief RAII, move-only 2D GPU image backed by VMA, bundled with a default image view.
 *
 * L1 resource that owns a `VkImage`, a `VmaAllocation`, and a `VkImageView`, and frees all
 * three on destruction. Allocation is done through @ref veng::Image::create; the resulting object
 * is non-copyable and must be moved or held inside a @ref veng::ResourcePool copy slot.
 *
 * @ingroup resources
 */

#ifndef VENG_IMAGE_HPP
#define VENG_IMAGE_HPP

#include <cstdint>
#include <expected>
#include <vulkan-memory-allocator-hpp/vk_mem_alloc.hpp>
#include <vulkan/vulkan.hpp>

namespace veng
{
/**
 * @brief RAII, move-only 2D GPU image with a matching default image view.
 * @ingroup resources
 * @see ResourcePool
 */
class Image
{
	 public:
	/**
	 * @brief Allocate a device-local 2D image and a matching view spanning all mip levels.
	 *
	 * Creates a 2D image with `mip_levels` mips, 1 array layer, 1 sample, optimal tiling,
	 * and a view over the full mip range with the given `aspect`. When `mip_levels` > 1
	 * the usage must include `eTransferSrc | eTransferDst` so the mip chain can be
	 * generated by blitting between levels after upload. The default value of 1 preserves
	 * the single-level render-target behaviour.
	 *
	 * A view is created only when `usage` contains at least one view-capable flag
	 * (sampled, storage, colour/depth attachment, input attachment, or transient
	 * attachment); a transfer-only image gets a null view handle.
	 *
	 * @param allocator  The VMA allocator to allocate device memory from.
	 * @param device     The Vulkan logical device used to create the image view.
	 * @param extent     Width and height of the image in texels.
	 * @param format     Pixel format.
	 * @param usage      Vulkan image-usage flags.
	 * @param aspect     View aspect mask (colour or depth).
	 * @param mip_levels Number of mip levels; 0 is treated as 1.
	 * @return The constructed @ref veng::Image on success, or the `vk::Result` error code on failure.
	 */
	[[nodiscard]] static std::expected<Image, vk::Result> create(
		vma::Allocator allocator, vk::Device device, vk::Extent2D extent, vk::Format format, vk::ImageUsageFlags usage,
		vk::ImageAspectFlags aspect = vk::ImageAspectFlagBits::eColor, std::uint32_t mip_levels = 1);

	Image(const Image&)			   = delete;
	Image& operator=(const Image&) = delete;
	Image(Image&& other) noexcept;
	Image& operator=(Image&& other) noexcept;
	~Image();

	/// @brief The underlying Vulkan image handle.
	[[nodiscard]] vk::Image image() const noexcept { return m_image; }
	/// @brief The default image view spanning all mip levels, or a null handle for transfer-only images.
	[[nodiscard]] vk::ImageView view() const noexcept { return m_view; }
	/// @brief The pixel format of the image.
	[[nodiscard]] vk::Format format() const noexcept { return m_format; }
	/// @brief The width and height of the image in texels.
	[[nodiscard]] vk::Extent2D extent() const noexcept { return m_extent; }
	/// @brief The number of mip levels in the image.
	[[nodiscard]] std::uint32_t mip_levels() const noexcept { return m_mip_levels; }

	 private:
	Image(vma::Allocator allocator, vk::Device device, vk::Image image, vma::Allocation allocation, vk::ImageView view,
		  vk::Format format, vk::Extent2D extent, std::uint32_t mip_levels) noexcept;
	void destroy() noexcept;

	vma::Allocator	m_allocator;
	vk::Device		m_device;
	vk::Image		m_image;
	vma::Allocation m_allocation;
	vk::ImageView	m_view;
	vk::Format		m_format;
	vk::Extent2D	m_extent;
	std::uint32_t	m_mip_levels;
};
} // namespace veng

#endif // VENG_IMAGE_HPP
