# CompilerSettings.cmake
# Contains compiler flag configuration based on cache variables
#
# Provides:
# - apply_compiler_warnings(target)
# - apply_error_on_warnings(target)
# - apply_sanitizer(target sanitizer_type)
# - apply_lto(target)

function(apply_compiler_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
endfunction()

function(apply_error_on_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /WX)
    else()
        target_compile_options(${target} PRIVATE -Werror)
    endif()
endfunction()

function(apply_sanitizer target sanitizer_type)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        if(sanitizer_type STREQUAL "address")
            target_compile_options(${target} PRIVATE -fsanitize=address)
            target_link_options(${target} PRIVATE -fsanitize=address)
        elseif(sanitizer_type STREQUAL "thread")
            target_compile_options(${target} PRIVATE -fsanitize=thread)
            target_link_options(${target} PRIVATE -fsanitize=thread)
        elseif(sanitizer_type STREQUAL "undefined")
            target_compile_options(${target} PRIVATE -fsanitize=undefined)
            target_link_options(${target} PRIVATE -fsanitize=undefined)
        else()
            message(FATAL_ERROR "Unknown sanitizer type: ${sanitizer_type}")
        endif()
    else()
        message(WARNING "Sanitizers are not supported for compiler '${CMAKE_CXX_COMPILER_ID}'")
    endif()
endfunction()

function(apply_lto target)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR MSVC)
        set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
    endif()
endfunction()
